### ISSUE TITLE
hatop download location out of date

### ISSUE THREAD

**Issue by conrado** [shufo/ansible-haproxy-keepalived#1]
ASK [Ensure hatop binary is downloaded] ***************************************
fatal: [haproxy1]: FAILED! => {"changed": false, "dest": "/tmp", "failed": true, "gid": 0, "group": "root", "mode": "01777", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 0, "url": "http://hatop.googlecode.com/files/hatop-0.7.7.tar.gz"}

**Comment by shufo** [comment]
#2 fixed this.
